// Run after npm run build. Uses real traffic records; GPS motion is test-only input.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const dist=path.resolve(process.argv[2]||'dist');
const leaflet=process.env.KPMAP_TEST_LEAFLET||require.resolve('leaflet/dist/leaflet.js');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/traffic-2026-10-03.json')));
let watchStarts=0,watchClears=0,gpsCallback,gpsError,gpsOptions,fetches=0,failFetch=false,intervals=[],errors=[],now=Date.now();
class Resources extends ResourceLoader {
 fetch(url) {
  if(url.includes('/leaflet@1.9.4/dist/leaflet.js'))return Promise.resolve(fs.readFileSync(leaflet));
  if(url.startsWith('https://kpmap.test/')){
   const local=path.join(dist,new URL(url).pathname);
   if(fs.existsSync(local))return Promise.resolve(fs.readFileSync(local));
  }
  return null;
 }
}
const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.detail?.stack||e.message));vc.on('error',(...args)=>{if(!failFetch)errors.push(args.join(' '));});
const dom=new JSDOM(fs.readFileSync(path.join(dist,'index.html'),'utf8'),{url:'https://kpmap.test/',runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
 w.Date.now=()=>now;
 Object.defineProperties(w.HTMLElement.prototype,{clientWidth:{get(){return this.id==='m'?1280:1280;}},clientHeight:{get(){return this.id==='m'?(this.classList.contains('map-fullscreen')?900:640):900;}}});
 w.HTMLCanvasElement.prototype.getContext=function(){return new Proxy({canvas:this},{get:(o,k)=>k in o?o[k]:()=>{}});};
 w.fetch=async()=>{fetches++;if(failFetch)throw new Error('test offline');return {ok:true,json:async()=>JSON.parse(JSON.stringify(fixture))};};
 w.navigator.geolocation={watchPosition(callback,error,options){watchStarts++;gpsCallback=callback;gpsError=error;gpsOptions=options;return 1;},clearWatch(){watchClears++;}};
 w.setInterval=(fn,ms)=>{intervals.push({fn,ms});return intervals.length;};
 Object.defineProperty(w.document,'hidden',{get:()=>false});
}});
const w=dom.window,wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const builtHtml=fs.readFileSync(path.join(dist,'index.html'),'utf8');
const dataStart=builtHtml.indexOf('const D=')+8;
assert(dataStart>=8,'Built route data is embedded in the map page');
let depth=0,inString=false,escaped=false,dataEnd=-1;
for(let i=dataStart;i<builtHtml.length;i++){const c=builtHtml[i];if(inString){if(escaped)escaped=false;else if(c.charCodeAt(0)===92)escaped=true;else if(c==='"')inString=false;}else if(c==='"')inString=true;else if(c==='{')depth++;else if(c==='}'&&--depth===0){dataEnd=i+1;break;}}
assert(dataEnd>dataStart,'Built route data is valid JSON');
const routeData=JSON.parse(builtHtml.slice(dataStart,dataEnd)),hi=routeData.hiroshima_iwakuni;
assert.equal(hi.quality,'osm-road-aligned');
assert.equal(hi.marks.length,26,'Hiroshima-Iwakuni keeps its existing 0–2.5 KP range');
assert(Math.abs(hi.marks[0][1]-34.336845)<.00001&&Math.abs(hi.marks[0][2]-132.294527)<.00001,'Hiroshima-Iwakuni 0 KP is at Hatsukaichi JCT');
assert(Math.abs(hi.marks.at(-1)[1]-34.3451588)<.00001&&Math.abs(hi.marks.at(-1)[2]-132.3131984)<.00001,'KP increases toward Hatsukaichi IC, not toward the JCT');
assert(hi.marks.every((mark,i)=>mark[0]===Number((i/10).toFixed(1))),'KP input remains sorted at 0.1km spacing');
assert(Math.abs(hi.segs[0][0][0]-34.3451588)<.0001&&Math.abs(hi.segs[0][0][1]-132.3131984)<.0001,'Route starts at Hatsukaichi IC');
assert(Math.abs(hi.segs[0].at(-1)[0]-34.336845)<.0001&&Math.abs(hi.segs[0].at(-1)[1]-132.294527)<.0001,'Route ends at Hatsukaichi JCT');
let routeKm=0;for(let i=1;i<hi.segs[0].length;i++){const a=hi.segs[0][i-1],b=hi.segs[0][i];routeKm+=12742*Math.asin(Math.sqrt(Math.sin((b[0]-a[0])*Math.PI/360)**2+Math.cos(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.sin((b[1]-a[1])*Math.PI/360)**2));}
assert(routeKm>1.9&&routeKm<2.5,'Corrected IC–JCT geometry follows the roughly 2km branch');

async function until(check,label){for(let i=0;i<100;i++){if(check())return;await wait(20);}throw new Error('Timed out: '+label);}
function gps(lat,lon,speed,heading,accuracy=8){now+=1000;gpsCallback({timestamp:now,coords:{latitude:lat,longitude:lon,speed,heading,accuracy}});}
async function main(){
 await until(()=>w.document.querySelector('.map-tool')&&w.document.querySelector('.traffic-event-marker'),'scripts');
 const doc=w.document,map=w.eval('map');
 assert.deepEqual(errors,[]);
 await wait(80);
 const markerBefore=doc.querySelector('.traffic-event-marker');
 doc.querySelector('#trafficRefresh').click();await wait(30);
 assert.equal(doc.querySelector('.traffic-event-marker'),markerBefore,'Identical feed preserves marker DOM instead of rebuilding');
 assert.equal(doc.querySelector('#locationPanel').parentElement,doc.querySelector('#m'),'Location summary stays inside the map for fullscreen');
 assert.equal(doc.querySelector('#locationKp').nextElementSibling,null);
 assert.equal(doc.querySelector('.location-road-stack small').textContent,'最寄りKP');
 assert.equal(w.getComputedStyle(doc.querySelector('.location-road-stack')).display,'flex');
 assert.equal(w.getComputedStyle(doc.querySelector('.location-road-stack')).flexDirection,'column');
 assert.equal(w.getComputedStyle(doc.querySelector('.location-main')).alignItems,'flex-end');
 assert.equal(w.getComputedStyle(doc.querySelector('.location-summary')).alignItems,'flex-end');
 assert.equal(w.getComputedStyle(doc.querySelector('#locationKp')).lineHeight,w.getComputedStyle(doc.querySelector('#locationRoad')).lineHeight,'KP and road share a line box height');
 assert.equal(doc.querySelector('#locationDirection').previousElementSibling.className,'location-main');
 assert(doc.querySelector('.next-facilities'),'Next facilities panel stays in the upper toolbar');
 assert.equal(doc.querySelector('.traffic-new'),null,'Initial events are not all new');
 map.setZoom(14,{animate:false});await wait(60);
 assert(doc.querySelector('.detail-label'),'One wider zoom now reveals TN and bridge details');
 assert.equal(w.getComputedStyle(doc.querySelector('.detail-label')).fontSize,'12px');
 assert.equal(w.getComputedStyle(doc.querySelector('.detail-label')).letterSpacing,'.12em');
 assert(doc.querySelector('.detail-label').style.getPropertyValue('--detail-angle'),'Detail angle follows local road tangent');
 assert(Object.values(map._layers).some(l=>l._kpmapBaseWeight!==undefined&&l.options.weight>l._kpmapBaseWeight),'Zoomed road strokes get thicker');
 assert.equal(w.getComputedStyle(doc.querySelector('.facility')).fontSize,'12px');
 assert.equal(map.getPane('detailLabelPane').parentElement,map.getPane('markerPane').parentElement);
 assert(+map.getPane('detailLabelPane').style.zIndex<+map.getPane('kpPane').style.zIndex);
 map.setZoom(12,{animate:false});await wait(60);
 assert.equal(doc.querySelector('.detail-label'),null,'Wide view hides detail labels');
 for(const [z,expected] of [[9,'.65'],[10,'.72'],[11,'.8'],[12,'.9'],[13,'1']]){map.setZoom(z,{animate:false});await wait(30);assert.equal(doc.querySelector('#m').style.getPropertyValue('--kpmap-label-scale'),expected);}map.setZoom(12,{animate:false});await wait(60);
 assert.equal(doc.querySelector('#q').value,'');
 assert.equal(doc.querySelector('#gmap').disabled,true);
 assert.equal(doc.querySelector('#trafficRadius').value,'20');
 const resolved=fixture.events.filter(e=>['山陽道','中国道','広島道','広島岩国道路'].includes(e.road));
 const locator=require('../traffic-location.js');locator.resolveEvents(resolved,w.eval('D'),require('../traffic-landmarks.json'),{'山陽道':'sanyo','中国道':'chugoku','広島道':'hiroshima','広島岩国道路':'hiroshima_iwakuni'});
 const expectedMarkers=new Set(resolved.filter(e=>e.mapPoint).map(e=>e.mapPoint.join(','))).size;
 assert(doc.querySelectorAll('.traffic-event-marker').length<=expectedMarkers,'Nearby events can share markers');assert.equal(doc.querySelectorAll('.traffic-anchor-line').length,0,'Offset connector lines are removed');
 assert.equal([...doc.querySelectorAll('.traffic-event-marker')].reduce((n,e)=>n+(Number(e.querySelector('.traffic-cluster-count')?.textContent)||1),0),32,'All records are retained in visible counts');
 assert(doc.querySelector('.traffic-cluster-count'),'Equal coordinates have a visible count');
 assert.equal(doc.querySelectorAll('.facility').length,135,'Existing four-route facility labels must remain');
 assert(doc.querySelector('#trafficUpdated').textContent.includes('更新（取得時刻）'));
 assert.equal(doc.querySelectorAll('.traffic-age').length,0,'Fetch time must never be displayed as event age');
 assert(gpsOptions.enableHighAccuracy&&gpsOptions.maximumAge===0);
 assert(doc.querySelector('#r').style.color,'Selected road uses its map color');
 const trafficMarkers=Object.values(map._layers).filter(x=>x.options?.pane?.startsWith('trafficPriority'));
 const centers=trafficMarkers.map(x=>{const p=map.latLngToContainerPoint(x.getLatLng()),a=x.options.icon.options.iconAnchor;return [p.x-a[0],p.y-a[1]]});
 for(let i=0;i<centers.length;i++)for(let j=i+1;j<centers.length;j++)assert(Math.abs(centers[i][0]-centers[j][0])>=23 || Math.abs(centers[i][1]-centers[j][1])>=23,'Every traffic event must remain individually visible');
 const host=map.getPane('markerPane').parentElement;
 assert.equal(map.getPane('kpPane').parentElement,host);
 assert.equal(map.getPane('facilityPane').parentElement,host);
 assert(+map.getPane('kpPane').style.zIndex<+map.getPane('facilityPane').style.zIndex,'Facilities sit above ordinary KP labels');
 assert(+map.getPane('facilityPane').style.zIndex<+map.getPane('selectedKpPane').style.zIndex,'Selected KP labels stay above facilities');
 assert.equal(doc.querySelector('.location-main').children[0].className,'location-road-stack');
 for(let rank=0;rank<=5;rank++){const pane=map.getPane('trafficPriority'+rank);if(pane){assert.equal(pane.parentElement,host);assert(+pane.style.zIndex>+map.getPane('facilityPane').style.zIndex);}}
 assert(+map.getPane('trafficPopupPane').style.zIndex>+map.getPane('kpPane').style.zIndex);
 assert.equal(map.getPane('trafficPopupPane').parentElement,host);
 const sharedMarker=Object.values(map._layers).find(x=>x.getElement?.()?.querySelector('.traffic-cluster-count'));
 sharedMarker.openPopup();assert.equal(sharedMarker.getPopup().getElement().querySelectorAll('.traffic-shared-event').length,Number(sharedMarker.getElement().querySelector('.traffic-cluster-count').textContent),'Shared popup includes every event');sharedMarker.closePopup();
 const trafficMarker=[...map._layers?Object.values(map._layers):[]].find(x=>x.options?.pane?.startsWith('trafficPriority'));
 trafficMarker.openPopup();
 assert.equal(trafficMarker.getPopup().getElement().parentElement,map.getPane('trafficPopupPane'),'Popup must share the KP stacking context at a higher level');
 trafficMarker.closePopup();
 trafficMarker.getElement().click();
 assert(trafficMarker.isPopupOpen(),'Clicking the traffic icon must open its popup');
 trafficMarker.closePopup();
 assert.equal(doc.querySelector('.map-fullscreen-shortcut').textContent,'F');assert.equal(w.getComputedStyle(doc.querySelector('.map-fullscreen-shortcut')).pointerEvents,'none');
 const tools=[...doc.querySelectorAll('.map-tool')];assert.equal(tools.length,3);
 assert(tools[0].title.includes('全画面')&&tools[1].title.includes('追いかけ')&&tools[2].title.includes('進行方向'));
 gps(34.4557,132.721,1,180);
 assert.deepEqual(Object.values(map._layers).filter(x=>x.options?.pane==='distanceRingPane'&&x.getRadius).map(x=>x.getRadius()),[5000,10000],'Distance rings use exact meter radii');
 assert.equal(map.getPane('distanceRingPane').parentElement,map.getPane('overlayPane').parentElement,'Range rings rotate with geographic overlays');
 assert(!/E2|E74/.test(doc.querySelector('#locationRoad').textContent),'Road overlay omits route codes');
 assert.equal(w.KPMAPLocation.getLatest().heading,null,'Walking must not determine direction');
 const nearbyText=doc.querySelector('#trafficCount').textContent;
 assert(nearbyText.startsWith('2件'),'Nearby traffic radius must still work');
 assert(doc.querySelector('.traffic-regulation-group'));
 tools[1].click();
 assert.equal(tools[1].getAttribute('aria-pressed'),'true');
 gps(34.4557,132.72101,1,270);
 assert.equal(w.KPMAPLocation.getLatest().heading,null);
 assert(Math.abs(map.getCenter().lat-34.4557)<.0001,'Follow should center on GPS');
 tools[2].click();
 gps(34.4557,132.72112,10,90);
 assert.equal(w.KPMAPLocation.getLatest().directionStatus,'unavailable','36km/h must not count as vehicle evidence');
 gps(34.4557,132.7212,40/3.6,90);
 assert.equal(w.KPMAPLocation.getLatest().directionStatus,'judging','40km/h boundary counts');
 gps(34.4557,132.72121,1,90);
 gps(34.4557,132.72125,12,90);
 assert.equal(doc.querySelector('#locationDirection').textContent,'上り/下り　判定中');
 assert.equal(w.KPMAPLocation.getLatest().heading,null,'One vehicle sample must not be sufficient');
 for(let second=1;second<30;second++)gps(34.4557,132.72125+second*.00013,12,90);
 assert.equal(w.KPMAPLocation.getLatest().heading,null,'29 seconds is not sufficient');
 gps(34.4557,132.72515,12,90);
 assert.equal(w.KPMAPLocation.getLatest().heading,90);
 assert.equal(w.KPMAPLocation.getLatest().directionStatus,'ready');
 assert(doc.querySelector('.next-facility-item'),'Confirmed driving direction produces upcoming facilities');
 gps(34.4557,132.72516,1,180);
 assert.equal(w.KPMAPLocation.getLatest().heading,90,'Walking retains confirmed vehicle heading');
 gps(34.4557,132.7253,12,270);
 assert.equal(w.KPMAPLocation.getLatest().directionStatus,'judging');
 gps(34.4557,132.72531,10,270);
 gps(34.4557,132.72544,12,90);
 assert.equal(w.KPMAPLocation.getLatest().directionStatus,'judging','Dropping below 40 resets confirmation');
 await wait(1200);
 assert(Math.abs(map.getBearing()-270)<2,'Eastbound heading must rotate north to the left');
 const center=map.latLngToContainerPoint(map.getCenter());
 const east=map.latLngToContainerPoint([map.getCenter().lat,map.getCenter().lng+.001]);
 assert(east.y<center.y&&Math.abs(east.x-center.x)<4,'East should render at the top');
 const northMarker=Object.values(map._layers).find(x=>x.getElement?.()?.classList.contains('distance-compass-tag')&&x.getElement().textContent==='N');
 assert(northMarker,'All four compass labels exist');
 const north=map.latLngToContainerPoint(northMarker.getLatLng());assert(north.x<center.x&&Math.abs(north.y-center.y)<15,'N follows geographic north to the left when driving east');
 assert.equal(Object.values(map._layers).find(x=>x.options?.pane==='distanceRingPane'&&x.getRadius).options.color,'#c94a58');
 const kp=doc.querySelector('.kplabel');kp.click();
 assert(w.eval('pickedKp')&&doc.querySelector('#gmap').disabled===false,'KP click and Google Map action must survive rotation');
 assert.equal(doc.querySelector('.kplabel.picked').closest('.leaflet-pane'),map.getPane('selectedKpPane'),'Selected KP must move above other overlays');
 assert.equal(map.getPane('selectedKpPane').parentElement,host);
 assert(+map.getPane('selectedKpPane').style.zIndex>+map.getPane('trafficPopupPane').style.zIndex);
 assert.equal(w.getComputedStyle(doc.querySelector('.kpstem')).display,'none');
 const input=doc.querySelector('#q');input.value='292';input.dispatchEvent(new w.Event('input',{bubbles:true}));
 assert.equal(doc.querySelector('#go').disabled,false);
 doc.querySelector('#go').click();
 assert.equal(w.eval('pickedKp')[2],292);
 assert.equal(map.getZoom(),12,'Existing KP jump zoom must remain unchanged');
 assert.equal(doc.querySelectorAll('.leaflet-selectedKp-pane .kplabel.picked').length,1,'KP input must update the single foreground selection');
 assert.equal(doc.querySelectorAll('.leaflet-selectedKp-pane .kplabel:not(.picked)').length,0,'Old selection must return to its ordinary pane');
 assert.equal(tools[1].getAttribute('aria-pressed'),'false','KP jump must stop following');
 tools[2].click();assert.equal(map.getBearing(),0,'North-up switch must work');
 tools[0].click();await wait(80);
 assert(doc.querySelector('#m').classList.contains('map-fullscreen'));
 assert(doc.body.classList.contains('kpmap-fullscreen-open'));
 assert.equal(doc.querySelector('.map-fullscreen-action button').disabled,false,'Google Map remains available in fullscreen');
 assert(doc.querySelector('.map-fullscreen-google').classList.contains('gmap-selected-action'));
 assert(doc.querySelector('.map-fullscreen-action').parentElement.classList.contains('leaflet-top'));
 doc.dispatchEvent(new w.KeyboardEvent('keydown',{key:'f'}));await wait(80);
 assert(!doc.querySelector('#m').classList.contains('map-fullscreen'));
 input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'f',bubbles:true}));await wait(20);
 assert(!doc.querySelector('#m').classList.contains('map-fullscreen'),'Typing F in input must not toggle');
 doc.dispatchEvent(new w.KeyboardEvent('keydown',{key:'F'}));await wait(80);
 assert(doc.querySelector('#m').classList.contains('map-fullscreen'));
 doc.dispatchEvent(new w.KeyboardEvent('keydown',{key:'f',repeat:true}));await wait(20);
 assert(doc.querySelector('#m').classList.contains('map-fullscreen'),'Held key must not repeatedly toggle');
 doc.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));await wait(80);
 assert(!doc.querySelector('#m').classList.contains('map-fullscreen'));
 tools[1].click();map.fire('dragstart');assert.equal(tools[1].getAttribute('aria-pressed'),'false','Manual pan stops following');
 gpsError({code:2});
 assert.equal(doc.querySelector('#locationDirection').textContent,'上り/下り　取得不可');
 const tile=Object.values(map._layers).find(l=>l instanceof w.L.TileLayer);
 assert.equal(tile.options.updateWhenZooming,false,'Pinch zoom defers intermediate-scale requests');
 const D=w.eval('D');
 for(const density of [10,5,2,1,.5,.1])for(const key of ['sanyo','chugoku','hiroshima','hiroshima_iwakuni']){
  const picked=w.eval('pickedKp');
  const expected=D[key].marks.filter(x=>w.eval('showK')(x[0],density));
  const selected=picked&&D[key].marks.find(x=>x[0]===picked[2]&&x[1]===picked[0]&&x[2]===picked[1]);if(selected&&!expected.includes(selected))expected.push(selected);
  assert.deepEqual(Array.from(w.eval('kpRows')(key,density),x=>x[0]),Array.from(expected,x=>x[0]),'Cached KP density keeps the exact original KP set');
 }
 const oldTime=doc.querySelector('#trafficUpdated').dateTime;
 failFetch=true;doc.querySelector('#trafficRefresh').click();await wait(30);
 assert.equal([...doc.querySelectorAll('.traffic-event-marker')].reduce((n,e)=>n+(Number(e.querySelector('.traffic-cluster-count')?.textContent)||1),0),32,'Failed update preserves every traffic record');
 assert.equal(doc.querySelector('#trafficUpdated').dateTime,oldTime,'Failed update must not claim a fresh timestamp');
 assert(doc.querySelector('#trafficUpdated').classList.contains('is-stale'));
 failFetch=false;
 const auto=intervals.find(x=>x.ms===60000);assert(auto);await auto.fn();await wait(30);
 assert(!doc.querySelector('#trafficUpdated').classList.contains('is-stale'));
 assert(!doc.querySelector('#trafficMeta').textContent.includes('失敗'),'Identical successful retry clears the failure message');
 assert(fetches>=3,'Initial, manual and automatic requests must run');
 map.setView([34.7,132.5],12,{animate:false});const recenterZoom=map.getZoom();
 const beforeRestart=watchStarts;now+=31000;
 doc.querySelector('.map-recenter').click();assert(watchStarts>beforeRestart,'Stale watch must restart on recenter');assert(watchClears>0);
 gps(34.4557,132.7252,0,0);assert(Math.abs(map.getCenter().lat-34.4557)>.01,'Recenter starts a slide instead of an instant jump');assert.equal(map.getZoom(),recenterZoom,'Recenter preserves scale');await until(()=>Math.abs(map.getCenter().lat-34.4557)<.0001,'Animated recenter reaches reacquired fix');
 gpsError({code:3});const beforeTimeoutRetry=watchStarts;doc.querySelector('.map-recenter').click();assert(watchStarts>beforeTimeoutRetry,'Timeout must permit retry');
 const extra={...fixture.events.find(e=>e.road==='山陽道'),reason:'test-only changed event'};fixture.events.push(extra);await auto.fn();await wait(30);
 assert(doc.querySelector('.traffic-map-new'),'New traffic is visibly flagged on the map');
 now+=10*60000;await auto.fn();await wait(30);assert.equal(doc.querySelector('.traffic-map-new'),null,'Badge expires at ten minutes without feed resets');
 fixture.events.push({...extra,category:'closed',categoryLabel:'通行止',reason:'test closure'});await auto.fn();await wait(30);
 const closure=Object.values(map._layers).find(x=>x.getElement?.()?.querySelector('.closure'));assert(closure,'Closure icon uses a warning effect');assert.equal(closure.options.icon.options.iconSize[0],32,'Closure icon is enlarged by twenty percent at wide zoom');assert(closure.getElement().querySelector('.closure-symbol').textContent==='×');assert(closure.getElement().querySelector('.closure').classList.contains('effect-color'));assert(closure.getElement().querySelector('.closure').classList.contains('effect-wave')); closure.getElement().click();assert(closure.isPopupOpen(),'Effect must not block popup clicks');
 assert.deepEqual(errors,[]);
 console.log('PASS: complete real-data page, individual markers, existing KP/Google/facility controls, GPS walk/vehicle rules, heading projection, follow/pan, fullscreen fallback and refresh failure recovery');
 dom.window.close();
}
main().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
